#!/bin/sh
# Writes THIRD_PARTY_LICENSES.txt: the licence texts of the Go standard
# library and of every module compiled into the angel binary. Run it (or
# `make licenses`) after changing dependencies, and commit the result.
set -eu

cd "$(dirname "$0")/.."
out=THIRD_PARTY_LICENSES.txt
main=$(go list -m)

# Licence-like files in a module's root directory, in a stable order.
licence_files() {
	ls "$1" | grep -iE '^(licen[cs]e|copying|notice|patents)(\.(md|txt))?$' | sort -f || true
}

section() { # title, dir
	printf '%s\n%s\n\n' "================================================================================" "$1"
	files=$(licence_files "$2")
	if [ -z "$files" ]; then
		echo "No licence file found in $2" >&2
		exit 1
	fi
	for f in $files; do
		printf -- '--- %s ---\n\n' "$f"
		cat "$2/$f"
		printf '\n\n'
	done
}

{
	echo "Third-party software in angel"
	echo
	echo "The angel binary includes the software listed below. Each section gives the"
	echo "module and version, followed by its licence and notice files, unchanged."
	echo
	echo "go-sql-driver/mysql is licensed under the Mozilla Public License 2.0. Its"
	echo "source code is available at https://github.com/go-sql-driver/mysql."
	echo
	echo "Generated by scripts/third-party-licenses.sh with $(go env GOVERSION)."
	echo

	section "Go standard library $(go env GOVERSION)" "$(go env GOROOT)"

	go list -deps -f '{{with .Module}}{{.Path}}{{end}}' . | sort -u | grep -vx "$main" |
		while read -r m; do
			section "$m $(go list -m -f '{{.Version}}' "$m")" "$(go list -m -f '{{.Dir}}' "$m")"
		done
} >"$out"

echo "wrote $out" >&2
